const actionTypes = {
  /*  PRODUCT ACTIONS START*/
  PRODUCT_LIST_REQUEST: "PRODUCT_LIST_REQUEST",
  PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
  PRODUCT_LIST_FAIL: "PRODUCT_LIST_FAIL",
  /*  PRODUCT ACTIONS END*/
  // LOGIN ACTIONS START
  USER_LOGIN_REQUEST: "SER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  //LOGIN ACTIONS END

  PRODUCTS_TOP_REQUEST: "PRODUCTS_TOP_REQUEST",
  PRODUCTS_TOP_SUCCESS: "PRODUCTS_TOP_SUCCESS",
  PRODUCTS_TOP_FAIL: "PRODUCTS_TOP_FAIL",

  PRODUCT_BY_ID_REQUEST: "PRODUCT_BY_ID_REQUEST",
  PRODUCT_BY_ID_SUCCESS: "PRODUCT_BY_ID_SUCCESS",
  PRODUCT_BY_ID_FAIL: "PRODUCT_BY_ID_FAIL",

  TYPE_REQUEST: "TYPE_REQUEST",
  TYPE_SUCCESS: "TYPE_SUCCESS",
  TYPE_FAIL: "TYPE_FAIL",

  TYPE_LOGOUT: "TYPE_LOGOUT",
};

export default actionTypes;
